version: "3.8"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
  server:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 2021:2021
    environment:
      - PGHOST=db
      - PGUSER=user
      - PGDATABASE=postgres
      - PGPASSWORD=pass
      - PGPORT=5432
